export const ORDER_CONTRACT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  PREPARING: 'PREPARING',
  SHIPPED: 'SHIPPED',
  DONE: 'DONE',
  CANCELED: 'CANCELED',
}

export const PAYMENT_CONTRACT_STATUS = {
  READY: 'READY',
  APPROVED: 'APPROVED',
  CANCELED: 'CANCELED',
  FAILED: 'FAILED',
}

export function normalizeOrderStatus(status) {
  const statusMap = {
    CREATED: ORDER_CONTRACT_STATUS.PENDING,
    PAYMENT_READY: ORDER_CONTRACT_STATUS.PENDING,
    PAYMENT_PENDING: ORDER_CONTRACT_STATUS.PENDING,
    PAID: ORDER_CONTRACT_STATUS.PAID,
    PREPARING: ORDER_CONTRACT_STATUS.PREPARING,
    SHIPPED: ORDER_CONTRACT_STATUS.SHIPPED,
    DONE: ORDER_CONTRACT_STATUS.DONE,
    PAYMENT_FAILED: ORDER_CONTRACT_STATUS.PENDING,
    FAILED: ORDER_CONTRACT_STATUS.PENDING,
    CANCELED: ORDER_CONTRACT_STATUS.CANCELED,
    EXPIRED: ORDER_CONTRACT_STATUS.CANCELED,
  }

  return statusMap[status] || status || ORDER_CONTRACT_STATUS.PENDING
}

export function normalizePaymentStatus(status) {
  const statusMap = {
    CREATED: PAYMENT_CONTRACT_STATUS.READY,
    PAYMENT_READY: PAYMENT_CONTRACT_STATUS.READY,
    PAYMENT_PENDING: PAYMENT_CONTRACT_STATUS.READY,
    READY: PAYMENT_CONTRACT_STATUS.READY,
    PAID: PAYMENT_CONTRACT_STATUS.APPROVED,
    SUCCESS: PAYMENT_CONTRACT_STATUS.APPROVED,
    APPROVED: PAYMENT_CONTRACT_STATUS.APPROVED,
    PAYMENT_FAILED: PAYMENT_CONTRACT_STATUS.FAILED,
    FAILED: PAYMENT_CONTRACT_STATUS.FAILED,
    CANCELED: PAYMENT_CONTRACT_STATUS.CANCELED,
    EXPIRED: PAYMENT_CONTRACT_STATUS.FAILED,
  }

  return statusMap[status] || status || PAYMENT_CONTRACT_STATUS.READY
}
