FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --extra dev --no-install-project

COPY src ./src
RUN uv sync --frozen --extra dev

EXPOSE 8000

CMD ["uv", "run", "fastapi", "dev", "src/project_cyan_ai/main.py", "--host", "0.0.0.0", "--port", "8000"]
