create table if not exists public.inquiry (
  inquiry_id bigint generated by default as identity primary key,
  inquiry_type text not null check (inquiry_type in ('SUPPORT', 'PRODUCT')),
  member_id bigint not null references public.member (member_id),
  goods_id bigint references public.goods (goods_id),
  title text not null,
  content text not null,
  is_secret boolean not null default false,
  status text not null default 'PENDING' check (status in ('PENDING', 'ANSWERED')),
  answer_content text,
  answered_by bigint references public.member (member_id),
  answered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint inquiry_product_goods_id_check check (
    (inquiry_type = 'PRODUCT' and goods_id is not null)
    or (inquiry_type = 'SUPPORT' and goods_id is null)
  )
);

create index if not exists inquiry_member_id_idx on public.inquiry (member_id);
create index if not exists inquiry_goods_id_idx on public.inquiry (goods_id);
create index if not exists inquiry_inquiry_type_idx on public.inquiry (inquiry_type);
