create table if not exists public.digital_goods_asset (
  asset_id bigint generated by default as identity primary key,
  goods_id bigint not null references public.goods (goods_id) on delete cascade,
  storage_bucket varchar(255) not null,
  object_path text not null,
  original_file_name text not null,
  content_type varchar(120) not null default 'application/octet-stream',
  file_size_bytes bigint not null default 0,
  checksum_sha256 char(64),
  display_name varchar(200),
  sort_order integer not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint digital_goods_asset_file_size_check check (file_size_bytes >= 0),
  constraint digital_goods_asset_checksum_check check (checksum_sha256 is null or checksum_sha256 ~ '^[0-9a-fA-F]{64}$'),
  constraint digital_goods_asset_object_unique unique (goods_id, storage_bucket, object_path)
);

create table if not exists public.digital_goods_entitlement (
  entitlement_id bigint generated by default as identity primary key,
  member_id bigint not null references public.member (member_id) on delete cascade,
  goods_id bigint not null references public.goods (goods_id) on delete cascade,
  order_id bigint references public.orders (order_id) on delete set null,
  order_item_id bigint references public.order_item (order_item_id) on delete set null,
  grant_source varchar(50) not null default 'ORDER',
  entitlement_status varchar(20) not null default 'ACTIVE',
  granted_at timestamptz not null default now(),
  revoked_at timestamptz,
  revoked_reason text,
  download_limit_per_period integer not null default 1,
  download_period_days integer not null default 30,
  last_downloaded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint digital_goods_entitlement_status_check
    check (entitlement_status in ('ACTIVE', 'PENDING', 'REVOKED', 'EXPIRED')),
  constraint digital_goods_entitlement_download_limit_check check (download_limit_per_period >= 0),
  constraint digital_goods_entitlement_period_check check (download_period_days >= 1)
);

create unique index if not exists digital_goods_entitlement_active_unique
  on public.digital_goods_entitlement (member_id, goods_id)
  where entitlement_status = 'ACTIVE';

create table if not exists public.digital_goods_download_request (
  request_id bigint generated by default as identity primary key,
  entitlement_id bigint not null references public.digital_goods_entitlement (entitlement_id) on delete cascade,
  member_id bigint not null references public.member (member_id) on delete cascade,
  goods_id bigint not null references public.goods (goods_id) on delete cascade,
  asset_id bigint not null references public.digital_goods_asset (asset_id) on delete restrict,
  request_status varchar(20) not null default 'GRANTED',
  requested_at timestamptz not null default now(),
  signed_url_expires_at timestamptz,
  download_token_hash char(64),
  requester_ip_hash char(64),
  user_agent_hash char(64),
  browser_fingerprint_hash char(64),
  denied_reason text,
  created_at timestamptz not null default now(),
  constraint digital_goods_download_request_status_check
    check (request_status in ('GRANTED', 'DENIED', 'EXPIRED', 'REVOKED')),
  constraint digital_goods_download_token_hash_check check (download_token_hash is null or download_token_hash ~ '^[0-9a-fA-F]{64}$'),
  constraint digital_goods_download_ip_hash_check check (requester_ip_hash is null or requester_ip_hash ~ '^[0-9a-fA-F]{64}$'),
  constraint digital_goods_download_user_agent_hash_check check (user_agent_hash is null or user_agent_hash ~ '^[0-9a-fA-F]{64}$'),
  constraint digital_goods_download_fingerprint_hash_check check (browser_fingerprint_hash is null or browser_fingerprint_hash ~ '^[0-9a-fA-F]{64}$')
);

create index if not exists idx_digital_goods_asset_goods_active
  on public.digital_goods_asset (goods_id, is_active, sort_order, asset_id);

create index if not exists idx_digital_goods_entitlement_member_status
  on public.digital_goods_entitlement (member_id, entitlement_status, granted_at desc);

create index if not exists idx_digital_goods_entitlement_order_item
  on public.digital_goods_entitlement (order_item_id)
  where order_item_id is not null;

create index if not exists idx_digital_goods_download_recent_granted
  on public.digital_goods_download_request (entitlement_id, requested_at desc)
  where request_status = 'GRANTED';

create index if not exists idx_digital_goods_download_member_goods
  on public.digital_goods_download_request (member_id, goods_id, requested_at desc);

create or replace function public.assert_digital_goods_asset()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.goods g
    join public.goods_category gc on gc.category_id = g.category_id
    where g.goods_id = new.goods_id
      and gc.fulfillment_type = 'DIGITAL'
  ) then
    raise exception 'Digital asset can only be attached to DIGITAL goods. goods_id=%', new.goods_id
      using errcode = '23514';
  end if;

  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_digital_goods_asset_assert on public.digital_goods_asset;
create trigger trg_digital_goods_asset_assert
before insert or update of goods_id, storage_bucket, object_path, is_active
on public.digital_goods_asset
for each row
execute function public.assert_digital_goods_asset();

create or replace function public.assert_digital_goods_entitlement()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_order_member_id bigint;
  v_order_item_goods_id bigint;
begin
  if not exists (
    select 1
    from public.goods g
    join public.goods_category gc on gc.category_id = g.category_id
    where g.goods_id = new.goods_id
      and gc.fulfillment_type = 'DIGITAL'
  ) then
    raise exception 'Digital entitlement can only be granted for DIGITAL goods. goods_id=%', new.goods_id
      using errcode = '23514';
  end if;

  if new.order_id is not null then
    select o.member_id
      into v_order_member_id
    from public.orders o
    where o.order_id = new.order_id;

    if v_order_member_id is null or v_order_member_id <> new.member_id then
      raise exception 'Digital entitlement order/member mismatch. order_id=% member_id=%', new.order_id, new.member_id
        using errcode = '23514';
    end if;
  end if;

  if new.order_item_id is not null then
    select oi.goods_id
      into v_order_item_goods_id
    from public.order_item oi
    where oi.order_item_id = new.order_item_id;

    if v_order_item_goods_id is null or v_order_item_goods_id <> new.goods_id then
      raise exception 'Digital entitlement order item/goods mismatch. order_item_id=% goods_id=%', new.order_item_id, new.goods_id
        using errcode = '23514';
    end if;
  end if;

  if new.entitlement_status <> 'ACTIVE' and new.revoked_at is null and new.entitlement_status in ('REVOKED', 'EXPIRED') then
    new.revoked_at = now();
  end if;

  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_digital_goods_entitlement_assert on public.digital_goods_entitlement;
create trigger trg_digital_goods_entitlement_assert
before insert or update of member_id, goods_id, order_id, order_item_id, entitlement_status
on public.digital_goods_entitlement
for each row
execute function public.assert_digital_goods_entitlement();

create or replace function public.enforce_digital_goods_download_request()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_entitlement public.digital_goods_entitlement%rowtype;
  v_asset public.digital_goods_asset%rowtype;
  v_period_start timestamptz;
  v_granted_count integer;
begin
  select *
    into v_entitlement
  from public.digital_goods_entitlement
  where entitlement_id = new.entitlement_id
  for update;

  if not found then
    raise exception 'Digital entitlement not found. entitlement_id=%', new.entitlement_id
      using errcode = '23503';
  end if;

  new.member_id = coalesce(new.member_id, v_entitlement.member_id);
  new.goods_id = coalesce(new.goods_id, v_entitlement.goods_id);

  if new.member_id <> v_entitlement.member_id or new.goods_id <> v_entitlement.goods_id then
    raise exception 'Digital download request does not match entitlement. entitlement_id=%', new.entitlement_id
      using errcode = '23514';
  end if;

  select *
    into v_asset
  from public.digital_goods_asset
  where asset_id = new.asset_id;

  if not found or v_asset.goods_id <> new.goods_id then
    raise exception 'Digital asset does not match goods. asset_id=% goods_id=%', new.asset_id, new.goods_id
      using errcode = '23514';
  end if;

  if new.request_status = 'GRANTED' then
    if v_entitlement.entitlement_status <> 'ACTIVE' then
      raise exception 'Digital entitlement is not active. entitlement_id=% status=%', new.entitlement_id, v_entitlement.entitlement_status
        using errcode = '23514';
    end if;

    if not v_asset.is_active then
      raise exception 'Digital asset is not active. asset_id=%', new.asset_id
        using errcode = '23514';
    end if;

    v_period_start = new.requested_at - make_interval(days => v_entitlement.download_period_days);

    select count(*)
      into v_granted_count
    from public.digital_goods_download_request request
    where request.entitlement_id = new.entitlement_id
      and request.request_status = 'GRANTED'
      and request.requested_at >= v_period_start
      and request.requested_at <= new.requested_at
      and (tg_op = 'INSERT' or request.request_id <> new.request_id);

    if v_granted_count >= v_entitlement.download_limit_per_period then
      raise exception 'Digital download limit exceeded. entitlement_id=% limit=% period_days=%',
        new.entitlement_id,
        v_entitlement.download_limit_per_period,
        v_entitlement.download_period_days
        using errcode = 'P0001';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_digital_goods_download_request_enforce on public.digital_goods_download_request;
create trigger trg_digital_goods_download_request_enforce
before insert or update of entitlement_id, asset_id, request_status, requested_at
on public.digital_goods_download_request
for each row
execute function public.enforce_digital_goods_download_request();

create or replace function public.touch_digital_goods_downloaded_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.request_status = 'GRANTED' then
    update public.digital_goods_entitlement
       set last_downloaded_at = greatest(coalesce(last_downloaded_at, new.requested_at), new.requested_at),
           updated_at = now()
     where entitlement_id = new.entitlement_id;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_digital_goods_download_request_touch on public.digital_goods_download_request;
create trigger trg_digital_goods_download_request_touch
after insert or update of request_status, requested_at
on public.digital_goods_download_request
for each row
execute function public.touch_digital_goods_downloaded_at();

create or replace function public.grant_digital_goods_entitlements_for_order(p_order_id bigint)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inserted_count integer := 0;
begin
  insert into public.digital_goods_entitlement (
    member_id,
    goods_id,
    order_id,
    order_item_id,
    grant_source,
    entitlement_status,
    granted_at
  )
  select
    o.member_id,
    oi.goods_id,
    o.order_id,
    min(oi.order_item_id) as order_item_id,
    'ORDER',
    'ACTIVE',
    now()
  from public.orders o
  join public.order_item oi on oi.order_id = o.order_id
  join public.goods g on g.goods_id = oi.goods_id
  join public.goods_category gc on gc.category_id = g.category_id
  where o.order_id = p_order_id
    and gc.fulfillment_type = 'DIGITAL'
  group by o.member_id, oi.goods_id, o.order_id
  on conflict do nothing;

  get diagnostics v_inserted_count = row_count;
  return v_inserted_count;
end;
$$;

create or replace function public.approve_checkout_payment(
  p_order_key text,
  p_payment_status text,
  p_order_status text,
  p_provider_payment_key text,
  p_payment_method text,
  p_provider text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id bigint;
  v_payment_id bigint;
  v_order_status text;
  v_payment_status text;
  v_managed_stock_count integer := 0;
  v_updated_stock_count integer := 0;
  v_digital_entitlement_count integer := 0;
begin
  select o.order_id, o.order_status
    into v_order_id, v_order_status
  from public.orders o
  where o.order_no = p_order_key
     or o.order_id::text = p_order_key
  order by o.order_id desc
  limit 1
  for update;

  if v_order_id is null then
    return jsonb_build_object(
      'status', 'NOT_SYNCED',
      'message', 'No order row matched the payment order key.',
      'orderRows', 0,
      'paymentRows', 0,
      'stockUpdatedRows', 0,
      'digitalEntitlementRows', 0
    );
  end if;

  select p.payment_id, p.payment_status
    into v_payment_id, v_payment_status
  from public.payment p
  where p.order_id = v_order_id
  order by p.payment_id desc
  limit 1
  for update;

  if upper(coalesce(v_order_status, '')) = 'PAID'
     or upper(coalesce(v_payment_status, '')) = 'APPROVED' then
    update public.orders
       set order_status = p_order_status
     where order_id = v_order_id;

    update public.payment
       set payment_status = p_payment_status,
           provider_payment_key = coalesce(nullif(p_provider_payment_key, ''), provider_payment_key),
           payment_method = coalesce(nullif(p_payment_method, ''), payment_method),
           provider = coalesce(nullif(p_provider, ''), provider)
     where payment_id = v_payment_id;

    select public.grant_digital_goods_entitlements_for_order(v_order_id)
      into v_digital_entitlement_count;

    return jsonb_build_object(
      'status', 'SYNCED',
      'message', 'Payment was already approved. Stock was not deducted again.',
      'orderRows', 1,
      'paymentRows', case when v_payment_id is null then 0 else 1 end,
      'stockUpdatedRows', 0,
      'stockSkipped', true,
      'digitalEntitlementRows', v_digital_entitlement_count
    );
  end if;

  with requested as (
    select oi.goods_id, sum(oi.quantity)::integer as quantity
    from public.order_item oi
    where oi.order_id = v_order_id
    group by oi.goods_id
  )
  select count(*)
    into v_managed_stock_count
  from requested r
  join public.goods_stock gs on gs.goods_id = r.goods_id
  where gs.current_stock is not null;

  with requested as (
    select oi.goods_id, sum(oi.quantity)::integer as quantity
    from public.order_item oi
    where oi.order_id = v_order_id
    group by oi.goods_id
  )
  update public.goods_stock gs
     set current_stock = gs.current_stock - requested.quantity
  from requested
  where gs.goods_id = requested.goods_id
    and gs.current_stock is not null
    and gs.current_stock >= requested.quantity;

  get diagnostics v_updated_stock_count = row_count;

  if v_updated_stock_count <> v_managed_stock_count then
    raise exception 'Not enough stock for order %.', p_order_key
      using errcode = 'P0001';
  end if;

  update public.orders
     set order_status = p_order_status
   where order_id = v_order_id;

  update public.payment
     set payment_status = p_payment_status,
         provider_payment_key = coalesce(nullif(p_provider_payment_key, ''), provider_payment_key),
         payment_method = coalesce(nullif(p_payment_method, ''), payment_method),
         provider = coalesce(nullif(p_provider, ''), provider)
   where payment_id = v_payment_id;

  select public.grant_digital_goods_entitlements_for_order(v_order_id)
    into v_digital_entitlement_count;

  return jsonb_build_object(
    'status', 'SYNCED',
    'message', 'Payment was approved and stock was deducted.',
    'orderRows', 1,
    'paymentRows', case when v_payment_id is null then 0 else 1 end,
    'stockUpdatedRows', v_updated_stock_count,
    'stockSkipped', false,
    'digitalEntitlementRows', v_digital_entitlement_count
  );
end;
$$;

comment on table public.digital_goods_asset is 'Downloadable files attached to DIGITAL goods.';
comment on table public.digital_goods_entitlement is 'Member-owned rights to access purchased digital goods.';
comment on table public.digital_goods_download_request is 'Audit log and rate-limit source for digital goods download URL requests.';
