create table if not exists public.customer_access_log (
  access_log_id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  method varchar(8) not null,
  path varchar(512) not null,
  status integer not null,
  duration_ms integer not null default 0,
  ip_address varchar(64),
  user_agent text,
  referer text,
  browser_fingerprint_hash varchar(64),
  blocked boolean not null default false
);

create index if not exists idx_customer_access_log_occurred_at
  on public.customer_access_log (occurred_at desc);

create index if not exists idx_customer_access_log_path
  on public.customer_access_log (path);

create index if not exists idx_customer_access_log_blocked
  on public.customer_access_log (blocked, occurred_at desc);

create index if not exists idx_customer_access_log_fingerprint
  on public.customer_access_log (browser_fingerprint_hash)
  where browser_fingerprint_hash is not null;

create table if not exists public.security_event (
  security_event_id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  event_type varchar(80) not null,
  severity varchar(20) not null default 'INFO',
  ip_address varchar(64),
  path varchar(512),
  user_agent text,
  detail text
);

create index if not exists idx_security_event_occurred_at
  on public.security_event (occurred_at desc);

create index if not exists idx_security_event_type
  on public.security_event (event_type, occurred_at desc);

comment on table public.customer_access_log is 'Project Cyan customer/admin HTTP access and consent-based page-view log.';
comment on table public.security_event is 'Project Cyan security events such as rate-limit blocks.';
