create table if not exists support_faq (
  faq_id bigint generated by default as identity primary key,
  category varchar(40) not null,
  question varchar(200) not null,
  answer text not null,
  sort_order integer not null default 100,
  visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_support_faq_visible_order
  on support_faq (visible, sort_order, faq_id);

insert into support_faq (category, question, answer, sort_order, visible)
select *
from (
  values
    (
      '주문/결제',
      'Q. 결제 후 주문 내역은 어디에서 확인하나요?',
      '로그인 후 마이페이지에서 주문 상태를 확인할 수 있습니다. 외부 간편결제나 결제사 화면에서 처리된 내역은 해당 결제사의 주문/결제 내역에도 함께 표시될 수 있습니다. 주문이 보이지 않으면 결제 시각, 결제 수단, 주문자 정보를 확인한 뒤 고객센터로 문의해 주세요.',
      10,
      true
    ),
    (
      '주문/결제',
      'Q. 무통장 입금 확인이 늦어지고 있습니다.',
      '무통장 입금은 입금자명, 금액, 주문 정보가 일치해야 확인됩니다. 입금 직후 바로 반영되지 않을 수 있으며, 입금자명이 다르거나 금액이 다르면 수동 확인이 필요합니다. 주문번호와 실제 입금자명을 함께 남겨주시면 확인 후 처리하겠습니다.',
      20,
      true
    ),
    (
      '주문/결제',
      'Q. 품절된 상품은 다시 입고되나요?',
      '재입고 예정이 있는 상품은 상품 상세, 공지, 아티스트 공식 채널 등을 통해 안내합니다. 별도 안내가 없는 경우 현재 확정된 재입고 일정이 없는 상태입니다.',
      30,
      true
    ),
    (
      '배송',
      'Q. 택배 외 다른 수령 방법이 있나요?',
      '현재 실물 굿즈는 택배 배송을 기준으로 운영합니다. 현장 수령이나 직접 방문 수령이 가능한 상품은 상품 상세 또는 별도 공지에서 안내합니다.',
      40,
      true
    ),
    (
      '배송',
      'Q. 제주/도서산간 추가 배송비가 있나요?',
      '배송지가 제주 또는 도서산간 지역이면 추가 배송비가 부과될 수 있습니다. 결제 단계에서 입력한 배송지를 기준으로 배송비가 계산됩니다.',
      50,
      true
    ),
    (
      '취소/교환/반품',
      'Q. 카드 환불은 언제 반영되나요?',
      '취소 또는 반품 처리가 완료되면 카드사로 환불 요청이 전달됩니다. 실제 승인 취소 반영까지는 카드사 정책에 따라 며칠이 걸릴 수 있습니다. 일정 기간이 지나도 반영되지 않으면 결제 정보와 주문번호를 고객센터로 알려주세요.',
      60,
      true
    ),
    (
      '취소/교환/반품',
      'Q. 제품 하자를 발견하면 어떻게 하나요?',
      '상품 수령 후 하자가 확인되면 상품명, 주문번호, 하자 부위 사진을 준비해 고객센터로 문의해 주세요. 상품 자체 불량으로 확인되면 교환, 반품, 보상 가능 범위를 안내합니다. 사용 중 발생한 손상이나 상세 페이지의 교환/반품 제한 사유에 해당하는 경우 처리가 제한될 수 있습니다.',
      70,
      true
    ),
    (
      '취소/교환/반품',
      'Q. 반품 수거가 진행되지 않습니다.',
      '교환 또는 반품 요청 후 택배 수거가 지연되면 주소, 연락처, 수거 가능 장소를 다시 확인해야 합니다. 고객센터로 주문번호와 수거 가능 일정을 남겨주시면 재접수 또는 택배사 확인을 진행합니다.',
      80,
      true
    ),
    (
      '디지털 굿즈',
      'Q. 디지털 굿즈는 환불이 가능한가요?',
      '다운로드, 열람, 코드 발급, 파일 제공 등 콘텐츠 제공이 시작된 뒤에는 환불이 제한될 수 있습니다. 제공 전 결제 오류나 중복 결제는 주문 정보 확인 후 처리합니다.',
      90,
      true
    )
) as seed(category, question, answer, sort_order, visible)
where not exists (
  select 1 from support_faq existing where existing.question = seed.question
);
