CREATE TABLE IF NOT EXISTS ai_goods_catalog_snapshot (
    snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_bucket TEXT,
    storage_path TEXT,
    catalog_url TEXT,
    url_expires_at TIMESTAMPTZ,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    item_count INTEGER NOT NULL DEFAULT 0,
    file_size_bytes BIGINT NOT NULL DEFAULT 0,
    status TEXT NOT NULL,
    error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_ai_goods_catalog_snapshot_success_generated
    ON ai_goods_catalog_snapshot (status, generated_at DESC, snapshot_id DESC);
