CREATE TABLE IF NOT EXISTS ai_hook_policy (
    policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hook TEXT NOT NULL,
    check_name TEXT NOT NULL,
    threshold_value TEXT NOT NULL,
    action TEXT NOT NULL,
    message TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    priority INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_hook_policy_enabled_priority
    ON ai_hook_policy (enabled, priority ASC, policy_id ASC);
