CREATE TABLE IF NOT EXISTS ai_llm_credential (
    credential_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_kind varchar(30) NOT NULL,
    ciphertext text NOT NULL,
    nonce varchar(100) NOT NULL,
    key_version varchar(40) NOT NULL,
    masked_hint varchar(100) NOT NULL,
    expires_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ai_llm_connection_profile (
    profile_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_name varchar(100) NOT NULL,
    provider varchar(30) NOT NULL CHECK (provider IN ('OPENAI', 'CLAUDE', 'CODEX_OAUTH', 'MOCK')),
    connection_type varchar(30) NOT NULL CHECK (connection_type IN ('API_KEY', 'OAUTH', 'NONE')),
    base_url varchar(1000),
    model varchar(200) NOT NULL,
    credential_id bigint REFERENCES ai_llm_credential(credential_id),
    profile_version bigint NOT NULL,
    last_tested_version bigint,
    last_tested_at timestamptz,
    last_test_status varchar(20),
    last_test_message varchar(1000),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ai_llm_connection_publication (
    publication_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_version bigint NOT NULL UNIQUE,
    profile_id bigint NOT NULL,
    profile_version bigint NOT NULL,
    provider varchar(30) NOT NULL,
    connection_type varchar(30) NOT NULL,
    base_url varchar(1000),
    model varchar(200) NOT NULL,
    credential_id bigint REFERENCES ai_llm_credential(credential_id),
    oauth_warning_acknowledged boolean NOT NULL DEFAULT false,
    rollback_from_publication_id bigint REFERENCES ai_llm_connection_publication(publication_id),
    published_at timestamptz NOT NULL DEFAULT now(),
    published_by varchar(100) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ai_llm_publication_profile_version
    ON ai_llm_connection_publication(profile_id, profile_version, publication_id DESC);

CREATE TABLE IF NOT EXISTS ai_llm_audit_log (
    audit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action varchar(80) NOT NULL,
    profile_id bigint,
    result varchar(20) NOT NULL,
    actor varchar(100) NOT NULL,
    client_ip varchar(100) NOT NULL,
    detail varchar(1000) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
