create table if not exists member_password_reset_token (
    password_reset_token_id bigint generated by default as identity primary key,
    member_id bigint not null references member (member_id) on delete cascade,
    token_hash text not null unique,
    expires_at timestamptz not null,
    used_at timestamptz,
    created_at timestamptz not null default now()
);

create index if not exists member_password_reset_token_member_id_idx
    on member_password_reset_token (member_id);

create index if not exists member_password_reset_token_expires_at_idx
    on member_password_reset_token (expires_at);
