CREATE TABLE IF NOT EXISTS virtual_chat_session (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    guide_id BIGINT NOT NULL DEFAULT 1,
    title VARCHAR(200),
    source_screen VARCHAR(50),
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS virtual_chat_message (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    speaker VARCHAR(20) NOT NULL,
    message_text TEXT NOT NULL,
    action VARCHAR(50),
    actions_json JSONB,
    metadata_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_virtual_chat_message_speaker
        CHECK (speaker IN ('USER', 'ASSISTANT', 'SYSTEM'))
);

CREATE TABLE IF NOT EXISTS virtual_recommendation (
    recommendation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    message_id BIGINT,
    goods_id BIGINT NOT NULL,
    request_text TEXT,
    recommendation_reason TEXT,
    rank_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_attribute
        WHERE attrelid = 'virtual_chat_session'::regclass
            AND attname = 'session_id'
            AND attidentity = ''
    ) THEN
        ALTER TABLE virtual_chat_session
            ALTER COLUMN session_id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM pg_attribute
        WHERE attrelid = 'virtual_chat_message'::regclass
            AND attname = 'message_id'
            AND attidentity = ''
    ) THEN
        ALTER TABLE virtual_chat_message
            ALTER COLUMN message_id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM pg_attribute
        WHERE attrelid = 'virtual_recommendation'::regclass
            AND attname = 'recommendation_id'
            AND attidentity = ''
    ) THEN
        ALTER TABLE virtual_recommendation
            ALTER COLUMN recommendation_id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

ALTER TABLE virtual_chat_session
    ALTER COLUMN guide_id SET DEFAULT 1;

ALTER TABLE virtual_chat_message
    ADD COLUMN IF NOT EXISTS actions_json JSONB;

ALTER TABLE virtual_chat_message
    ADD COLUMN IF NOT EXISTS metadata_json JSONB;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_virtual_chat_session_member'
    ) THEN
        ALTER TABLE virtual_chat_session
            ADD CONSTRAINT fk_virtual_chat_session_member
            FOREIGN KEY (member_id) REFERENCES member (member_id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_virtual_chat_message_session'
    ) THEN
        ALTER TABLE virtual_chat_message
            ADD CONSTRAINT fk_virtual_chat_message_session
            FOREIGN KEY (session_id) REFERENCES virtual_chat_session (session_id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'chk_virtual_chat_message_speaker'
    ) THEN
        ALTER TABLE virtual_chat_message
            ADD CONSTRAINT chk_virtual_chat_message_speaker
            CHECK (speaker IN ('USER', 'ASSISTANT', 'SYSTEM'));
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_virtual_recommendation_member'
    ) THEN
        ALTER TABLE virtual_recommendation
            ADD CONSTRAINT fk_virtual_recommendation_member
            FOREIGN KEY (member_id) REFERENCES member (member_id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_virtual_recommendation_session'
    ) THEN
        ALTER TABLE virtual_recommendation
            ADD CONSTRAINT fk_virtual_recommendation_session
            FOREIGN KEY (session_id) REFERENCES virtual_chat_session (session_id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_virtual_recommendation_message'
    ) THEN
        ALTER TABLE virtual_recommendation
            ADD CONSTRAINT fk_virtual_recommendation_message
            FOREIGN KEY (message_id) REFERENCES virtual_chat_message (message_id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_virtual_recommendation_goods'
    ) THEN
        ALTER TABLE virtual_recommendation
            ADD CONSTRAINT fk_virtual_recommendation_goods
            FOREIGN KEY (goods_id) REFERENCES goods (goods_id) ON DELETE CASCADE;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_virtual_chat_session_member_started
    ON virtual_chat_session (member_id, started_at DESC, session_id DESC);

CREATE INDEX IF NOT EXISTS idx_virtual_chat_message_session_created
    ON virtual_chat_message (session_id, created_at ASC, message_id ASC);

CREATE INDEX IF NOT EXISTS idx_virtual_recommendation_session_message_rank
    ON virtual_recommendation (session_id, message_id, rank_order ASC, recommendation_id ASC);
